# Site settings
title: Самоучитель по драм-машине Hydrogen
email: your-email@domain.com
description: "Самоучитель по свободной драм-машине Hydrogen"
baseurl: ""
url: "http://testhg.utkorose.ru"
destination: _publish_hydrogen
# Build settings
markdown: kramdown
permalink: pretty
